config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)

    if @post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def require_login
    unless user_signed_in?
      flash[:error] = "You must be signed in for this feature"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
  </head>

  <body>
    <%= link_to "Home", root_path %>
    
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete } %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/_post.html.erb
<h3><%= post.title %></h3>
<% if user_signed_in? %>
  <div>By: <%= post.user.email %></div>
<% end %>
<div><%= post.body %></div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% if user_signed_in? %>
  <div><%= link_to "New post", new_post_path %></div>
<% else %>
  <div>Sign in to view the authors of the posts</div>
<% end %>

<ul>
  <% @posts.reverse_each do |post| %>
    <li><%= render "post", post: post %></li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>